### ISSUE TITLE
Bug in the method pay of class OneTxPayment

### ISSUE THREAD

**Issue by javi-jamaa** [JoinColony/colonySDK#155]
the current code is:

pay(recipient, amount, teamId, tokenAddress) {
        const colonyClient = this.colony.getInternalColonyClient();
        const setReceipient = [].concat(recipient);
        const setTeamId = teamId || colony_js_1.Id.RootDomain;
        const setTokenAddress = tokenAddress
            ? [].concat(tokenAddress)
            : Array(setReceipient.length).fill(colonyClient.tokenClient.address);
        const setAmount = [].concat(amount);
        if (recipient.length !== setAmount.length) {
            throw new Error('recipient and amount arrays need to have the same size');
        }
        if (setTokenAddress.length !== setAmount.length) {
            throw new Error('amount and tokenAddress arrays need to have the same size');
        }

and the code correct is:
if (**setrecipient.length** !== setAmount.length) {
            throw new Error('recipient and amount arrays need to have the same size');
        }

**Comment by chmanie** [comment]
Thank you for reporting! This was fixed in 4d8c42d0c36ca4b406c84182f4c76c1fdc5c2360
